# Generated by Django 5.1.6 on 2025-03-05 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='training',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='training',
            name='sport_type',
            field=models.CharField(max_length=100, verbose_name='Вид спорта'),
        ),
    ]
