# Generated by Django 5.1.7 on 2025-03-31 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_training_options_alter_training_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={},
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_images/'),
        ),
        migrations.AddField(
            model_name='training',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
