# Generated by Django 5.1.7 on 2025-04-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_training_options_training_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_images/', verbose_name='Фото события'),
        ),
        migrations.AlterField(
            model_name='training',
            name='max_participants',
            field=models.PositiveIntegerField(default=10, verbose_name='Максимальное количество участников'),
        ),
    ]
