# Generated by Django 5.2 on 2025-05-08 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_training_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Тренировка завершена'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='participant_rating',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.training')),
            ],
            options={
                'unique_together': {('training', 'author')},
            },
        ),
    ]
