# Generated by Django 5.2 on 2025-05-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_training_is_finished_user_organizer_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizer_rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг организатора'),
        ),
    ]
