# Generated by Django 5.2 on 2025-05-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_organizer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.PositiveIntegerField(default=60, verbose_name='Продолжительность (в минутах)'),
        ),
    ]
